# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d2a2224c186d388f1953d20d65ac853018753db3dee376cc8069051544623072df078c79edcba75dd113a95df4e6e1aaa6a4e559cab462194a9673ab2126283

test:
  secret_key_base: 822d937b3d963fd80536f5df6c318254a34fd6af30afc42a7f7a243db9d1c2ecf97e3b303819d50449ff4d73565679ec959b36224cbaf2f43593b52458d597ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
